[MOBILE-3160] patch version 5.5.1
urbanairship/airship-flutter pull request #138
Opened 2022-08-02 21:38 UTC by Ulrico972

### What do these changes do?
Cherry-pick the two fixes we did on main

### Why are these changes necessary?
To release a patch version from 5.5.0

### How did you verify these changes?
Build and run

2022-08-02 22:02 UTC, rlepinski approved these changes

2022-08-02 22:02 UTC, rlepinski requested changes
Could we also update the SDK versions

2022-08-03 20:44 UTC, jyaganeh approved these changes

2022-08-03 21:45 UTC, rlepinski approved these changes

2022-08-03 21:46 UTC, merged